[[redirects]]
  from = "/api/v1/*"
  to = "https://api.notion.com/v1/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/v1/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,POST,PUT,DELETE,OPTIONS,PATCH"
    Access-Control-Allow-Headers = "Authorization, Notion-Version, Content-Type, X-Requested-With, Accept"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200